---
title: "olympic medal htest"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
```

## Feed in data

```{r olympics}
olympics <- read_csv("data/olympics.csv") |>
  drop_na(age)
```

## Data for test

```{r}

olympics_df <- olympics |>
  select(age, medal) |>
  mutate(medal = case_when(medal == "Gold" ~ 1,
                           medal == "Silver" ~ 1,
                           medal == "Bronze" ~ 1,
                           TRUE ~ 0)) |>
  mutate(age = case_when(age <25 ~ "Young",
                         age >=25 ~ "Old"))
olympics_df
```

## Summary of data

```{r}

olympics_summary <- olympics_df |>
  group_by(age) |>
  summarize(
    medal= sum(medal),
    n = n()
  ) |>
  arrange(desc(age))
olympics_summary
```

## Prop test

```{r}

test <- prop.test(olympics_summary$medal, olympics_summary$n,
                  correct = FALSE, alternative = c("greater"))
result <- tidy(test)
result
```

Given p-value \> 0.05, we fail to reject the null hypothesis and conclude that the proportion of athletes younger than 25 that win a medal is equal to the proportion of athletes of age 25 or older that win a medal.
